# Server
spring.application.name=medai-backend
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/medai_db
spring.datasource.username=medai_user
spring.datasource.password=medai_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=MedAI-Super-Secret-Key-Change-This-In-Production-2025-Must-Be-Very-Long-At-Least-256-Bits-For-Security
jwt.expiration=86400000

# Logging
logging.level.com.medai=DEBUG

ai.service.url=http://localhost:8000

# Jackson ? ?????????? ???????????? LocalDateTime
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.time-zone=UTC

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html